#!/bin/sh

sed -i 's|/usr/bin/plasmashell-fix|/usr/bin/plasmashell|g' /etc/xdg/autostart/org.kde.plasmashell.desktop

sed -i 's|big-logo|start-here-kde|g' /usr/share/plasma/plasmoids/org.biglinux.appsmenu/contents/config/main.xml 2> /dev/null > /dev/null

sed -i 's|big-logo|start-here-kde|g' /usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/main.xml 2> /dev/null > /dev/null

sed -i 's|big-logo|start-here-kde|g' /usr/share/plasma/plasmoids/org.kde.plasma.kickersupersimple/contents/config/main.xml 2> /dev/null > /dev/null

sed -i 's|big-logo|start-here-kde|g' /usr/share/plasma/plasmoids/org.kde.plasma.kickersimple/contents/config/main.xml 2> /dev/null > /dev/null

sed -i 's|big-logo|start-here-kde|g' /usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml 2> /dev/null > /dev/null

sed -i 's|big-logo|start-here-kde|g' /usr/share/plasma/plasmoids/org.kde.plasma.simplemenu/contents/config/main.xml 2> /dev/null > /dev/null
