#!/bin/sh

sed -i 's|/usr/bin/plasmashell$|/usr/bin/plasmashell-fix|g' /etc/xdg/autostart/org.kde.plasmashell.desktop

sed -i 's|/usr/bin/plasmashell --no-respawn|/usr/bin/plasmashell-fix|g' /usr/lib/systemd/user/plasma-plasmashell.service
